# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PIT.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='PIT.proto',
  package='teensy._3_1.pit',
  serialized_pb=_b('\n\tPIT.proto\x12\x0fteensy._3_1.pit\"\"\n\x05R_MCR\x12\x0c\n\x04MDIS\x18\x01 \x01(\x08\x12\x0b\n\x03\x46RZ\x18\x02 \x01(\x08\"0\n\x07R_TCTRL\x12\x0b\n\x03\x43HN\x18\x01 \x01(\x08\x12\x0b\n\x03TIE\x18\x02 \x01(\x08\x12\x0b\n\x03TEN\x18\x03 \x01(\x08\"\x15\n\x06R_TFLG\x12\x0b\n\x03TIF\x18\x01 \x01(\x08\"z\n\x0bTimerConfig\x12\r\n\x05LDVAL\x18\x01 \x01(\r\x12\x0c\n\x04\x43VAL\x18\x02 \x01(\r\x12\'\n\x05TCTRL\x18\x03 \x01(\x0b\x32\x18.teensy._3_1.pit.R_TCTRL\x12%\n\x04TFLG\x18\x04 \x01(\x0b\x32\x17.teensy._3_1.pit.R_TFLG\"0\n\tRegisters\x12#\n\x03MCR\x18\x01 \x01(\x0b\x32\x16.teensy._3_1.pit.R_MCR')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_R_MCR = _descriptor.Descriptor(
  name='R_MCR',
  full_name='teensy._3_1.pit.R_MCR',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='MDIS', full_name='teensy._3_1.pit.R_MCR.MDIS', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='FRZ', full_name='teensy._3_1.pit.R_MCR.FRZ', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=64,
)


_R_TCTRL = _descriptor.Descriptor(
  name='R_TCTRL',
  full_name='teensy._3_1.pit.R_TCTRL',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='CHN', full_name='teensy._3_1.pit.R_TCTRL.CHN', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='TIE', full_name='teensy._3_1.pit.R_TCTRL.TIE', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='TEN', full_name='teensy._3_1.pit.R_TCTRL.TEN', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=66,
  serialized_end=114,
)


_R_TFLG = _descriptor.Descriptor(
  name='R_TFLG',
  full_name='teensy._3_1.pit.R_TFLG',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='TIF', full_name='teensy._3_1.pit.R_TFLG.TIF', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=116,
  serialized_end=137,
)


_TIMERCONFIG = _descriptor.Descriptor(
  name='TimerConfig',
  full_name='teensy._3_1.pit.TimerConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='LDVAL', full_name='teensy._3_1.pit.TimerConfig.LDVAL', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='CVAL', full_name='teensy._3_1.pit.TimerConfig.CVAL', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='TCTRL', full_name='teensy._3_1.pit.TimerConfig.TCTRL', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='TFLG', full_name='teensy._3_1.pit.TimerConfig.TFLG', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=139,
  serialized_end=261,
)


_REGISTERS = _descriptor.Descriptor(
  name='Registers',
  full_name='teensy._3_1.pit.Registers',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='MCR', full_name='teensy._3_1.pit.Registers.MCR', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=263,
  serialized_end=311,
)

_TIMERCONFIG.fields_by_name['TCTRL'].message_type = _R_TCTRL
_TIMERCONFIG.fields_by_name['TFLG'].message_type = _R_TFLG
_REGISTERS.fields_by_name['MCR'].message_type = _R_MCR
DESCRIPTOR.message_types_by_name['R_MCR'] = _R_MCR
DESCRIPTOR.message_types_by_name['R_TCTRL'] = _R_TCTRL
DESCRIPTOR.message_types_by_name['R_TFLG'] = _R_TFLG
DESCRIPTOR.message_types_by_name['TimerConfig'] = _TIMERCONFIG
DESCRIPTOR.message_types_by_name['Registers'] = _REGISTERS

R_MCR = _reflection.GeneratedProtocolMessageType('R_MCR', (_message.Message,), dict(
  DESCRIPTOR = _R_MCR,
  __module__ = 'PIT_pb2'
  # @@protoc_insertion_point(class_scope:teensy._3_1.pit.R_MCR)
  ))
_sym_db.RegisterMessage(R_MCR)

R_TCTRL = _reflection.GeneratedProtocolMessageType('R_TCTRL', (_message.Message,), dict(
  DESCRIPTOR = _R_TCTRL,
  __module__ = 'PIT_pb2'
  # @@protoc_insertion_point(class_scope:teensy._3_1.pit.R_TCTRL)
  ))
_sym_db.RegisterMessage(R_TCTRL)

R_TFLG = _reflection.GeneratedProtocolMessageType('R_TFLG', (_message.Message,), dict(
  DESCRIPTOR = _R_TFLG,
  __module__ = 'PIT_pb2'
  # @@protoc_insertion_point(class_scope:teensy._3_1.pit.R_TFLG)
  ))
_sym_db.RegisterMessage(R_TFLG)

TimerConfig = _reflection.GeneratedProtocolMessageType('TimerConfig', (_message.Message,), dict(
  DESCRIPTOR = _TIMERCONFIG,
  __module__ = 'PIT_pb2'
  # @@protoc_insertion_point(class_scope:teensy._3_1.pit.TimerConfig)
  ))
_sym_db.RegisterMessage(TimerConfig)

Registers = _reflection.GeneratedProtocolMessageType('Registers', (_message.Message,), dict(
  DESCRIPTOR = _REGISTERS,
  __module__ = 'PIT_pb2'
  # @@protoc_insertion_point(class_scope:teensy._3_1.pit.Registers)
  ))
_sym_db.RegisterMessage(Registers)


# @@protoc_insertion_point(module_scope)
